Add a step to check idempotence

diff --git a/.github/workflows/ansible-playbook.yml b/.github/workflows/ansible-playbook.yml
--- a/.github/workflows/ansible-playbook.yml
+++ b/.github/workflows/ansible-playbook.yml
@@ -45,3 +45,11 @@ jobs:
         run: ansible-playbook -i hosts -vv localhost.yml
         env:
           ANSIBLE_FORCE_COLOR: '1'
+
+      - name: Check if the playbook is satisfied with Idempotence
+        run: |
+          idempotence=$(mktemp)
+          ansible-playbook main.yml | tee -a ${idempotence}
+          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
+        env:
+          ANSIBLE_FORCE_COLOR: '1'
